server:
  port: 9003
  servlet:
    context-path: /user-service/

spring:
  profiles:
    active: dev
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://ultimet-dev.cpm2ioqsiw9j.eu-north-1.rds.amazonaws.com:3306/ulti-met
    username: root
    password: Shreegeeks120714
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka

